service: workshop-${self:custom.name}

custom:
  name: ''
  email: ''

provider:
  name: aws
  runtime: nodejs12.x

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get